language: objective-c
osx_image: xcode10.3
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - IOS_SDK=iphonesimulator12.4
before_install:
  - gem install cocoapods
  - pod repo update
  - pod install
script:
  - xcodebuild -showsdks
  - xcodebuild -workspace Poly.xcworkspace -scheme 'Debug' -sdk $IOS_SDK build analyze
